/**
 * FOODIES Digital Menu — Official Menu Catalog
 * Premium, authentic fast-food restaurant menu data.
 * Specific, natural, ingredient-grounded descriptions without generic AI hype.
 */

export const MENU_CATEGORIES = [
  { id: 'all', name: 'ALL' },
  { id: 'vegetarian', name: 'VEGETARIAN' },
  { id: 'classic', name: 'CLASSIC' },
  { id: 'deluxe', name: 'DELUXE' },
];

export const MENU_ITEMS = [
  // --------------------------------------------------------------------------
  // VEGETARIAN PIZZA
  // --------------------------------------------------------------------------
  {
    id: 'margherita',
    name: 'Margherita',
    category: 'vegetarian',
    categoryName: 'Vegetarian Pizza',
    shortDesc: 'Tomato sauce, melted mozzarella, vine tomatoes & fresh basil',
    description: 'Crushed tomato sauce, double melted mozzarella, sliced vine tomatoes, and fresh basil leaves.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=600&q=80',
    alt: 'Fresh Margherita Pizza with melted mozzarella and tomato sauce',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 4.00, formattedPrice: '$4' },
      { size: 'MEDIUM', label: 'Medium', price: 6.00, formattedPrice: '$6' },
      { size: 'LARGE', label: 'Large', price: 8.00, formattedPrice: '$8' },
    ],
  },
  {
    id: 'veggie-feast',
    name: 'Veggie Feast',
    category: 'vegetarian',
    categoryName: 'Vegetarian Pizza',
    shortDesc: 'Crisp bell peppers, button mushrooms, onions, sweetcorn & olives',
    description: 'Crisp bell peppers, button mushrooms, sliced red onions, sweetcorn, black olives, and mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1576458088443-04a19bb13da6?auto=format&fit=crop&w=600&q=80',
    alt: 'Veggie Feast Pizza with peppers, mushrooms, and olives',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 5.00, formattedPrice: '$5' },
      { size: 'MEDIUM', label: 'Medium', price: 7.00, formattedPrice: '$7' },
      { size: 'LARGE', label: 'Large', price: 9.00, formattedPrice: '$9' },
    ],
  },
  {
    id: 'pizza-pie',
    name: 'Pizza Pie',
    category: 'vegetarian',
    categoryName: 'Vegetarian Pizza',
    shortDesc: 'Double-crust pie stuffed with seasoned veggies & mozzarella',
    description: 'Double-crust pie stuffed with seasoned garden vegetables, savory herbs, and bubbling mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1595708684082-a173bb3a06c5?auto=format&fit=crop&w=600&q=80',
    alt: 'Golden baked Pizza Pie with savory cheese filling',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 5.00, formattedPrice: '$5' },
      { size: 'MEDIUM', label: 'Medium', price: 7.00, formattedPrice: '$7' },
      { size: 'LARGE', label: 'Large', price: 9.00, formattedPrice: '$9' },
    ],
  },
  {
    id: 'roasted-veg',
    name: 'Roasted Veg',
    category: 'vegetarian',
    categoryName: 'Vegetarian Pizza',
    shortDesc: 'Fire-roasted sweet peppers, caramelized onions & roasted garlic',
    description: 'Fire-roasted sweet peppers, caramelized onions, roasted garlic, mozzarella, and Italian herbs.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    alt: 'Roasted Veg Pizza with caramelized peppers and onions',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 6.00, formattedPrice: '$6' },
      { size: 'MEDIUM', label: 'Medium', price: 9.00, formattedPrice: '$9' },
      { size: 'LARGE', label: 'Large', price: 11.00, formattedPrice: '$11' },
    ],
  },

  // --------------------------------------------------------------------------
  // CLASSIC PIZZA
  // --------------------------------------------------------------------------
  {
    id: 'bbq-steak',
    name: 'BBQ Steak',
    category: 'classic',
    categoryName: 'Classic Pizza',
    shortDesc: 'Tender steak strips, smoky barbecue drizzle & red onions',
    description: 'Tender steak strips, rich smoky barbecue sauce drizzle, sliced red onions, and melted mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
    alt: 'BBQ Steak Pizza with steak strips and smoky barbecue drizzle',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 5.00, formattedPrice: '$5' },
      { size: 'MEDIUM', label: 'Medium', price: 7.00, formattedPrice: '$7' },
      { size: 'LARGE', label: 'Large', price: 9.50, formattedPrice: '$9.50' },
    ],
  },
  {
    id: 'hawaiian',
    name: 'Hawaiian',
    category: 'classic',
    categoryName: 'Classic Pizza',
    shortDesc: 'Smoked cured ham, sweet golden pineapple & double mozzarella',
    description: 'Smoked cured ham, sweet golden pineapple chunks, crushed tomato sauce, and double mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    alt: 'Hawaiian Pizza with savory ham and pineapple',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 5.00, formattedPrice: '$5' },
      { size: 'MEDIUM', label: 'Medium', price: 7.00, formattedPrice: '$7' },
      { size: 'LARGE', label: 'Large', price: 9.00, formattedPrice: '$9' },
    ],
  },
  {
    id: 'mince-n-onion',
    name: 'Mince n Onion',
    category: 'classic',
    categoryName: 'Classic Pizza',
    shortDesc: 'Seasoned beef mince, sautéed sweet onions & melted mozzarella',
    description: 'Seasoned ground beef mince, slow-sautéed sweet onions, tomato base, and melted mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1588315029754-2dd089d39a1a?auto=format&fit=crop&w=600&q=80',
    alt: 'Mince n Onion Pizza with seasoned beef and caramelized onions',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 6.00, formattedPrice: '$6' },
      { size: 'MEDIUM', label: 'Medium', price: 9.00, formattedPrice: '$9' },
      { size: 'LARGE', label: 'Large', price: 11.00, formattedPrice: '$11' },
    ],
  },
  {
    id: 'chicken-mushroom',
    name: 'Chicken Mushroom',
    category: 'classic',
    categoryName: 'Classic Pizza',
    shortDesc: 'Grilled chicken breast pieces, button mushrooms & garlic butter',
    description: 'Grilled chicken breast pieces, sliced button mushrooms, garlic herb butter, and mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=600&q=80',
    alt: 'Chicken Mushroom Pizza with sliced mushrooms and chicken',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 5.00, formattedPrice: '$5' },
      { size: 'MEDIUM', label: 'Medium', price: 7.00, formattedPrice: '$7' },
      { size: 'LARGE', label: 'Large', price: 9.50, formattedPrice: '$9.50' },
    ],
  },
  {
    id: 'tropical-chicken',
    name: 'Tropical Chicken',
    category: 'classic',
    categoryName: 'Classic Pizza',
    shortDesc: 'Tender seasoned chicken, sweet pineapple & tangy tomato',
    description: 'Tender seasoned chicken, sweet pineapple pieces, tangy tomato sauce, and golden mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1574126154517-d1e0d89ef734?auto=format&fit=crop&w=600&q=80',
    alt: 'Tropical Chicken Pizza with chicken and sweet pineapple',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 5.00, formattedPrice: '$5' },
      { size: 'MEDIUM', label: 'Medium', price: 7.00, formattedPrice: '$7' },
      { size: 'LARGE', label: 'Large', price: 9.50, formattedPrice: '$9.50' },
    ],
  },
  {
    id: 'sweet-chilli',
    name: 'Sweet Chilli',
    category: 'classic',
    categoryName: 'Classic Pizza',
    shortDesc: 'Grilled chicken in sweet chilli glaze, bell peppers & onions',
    description: 'Grilled chicken tossed in sweet chilli glaze, crisp bell peppers, red onions, and mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=600&q=80',
    alt: 'Sweet Chilli Chicken Pizza with peppers and onions',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 5.00, formattedPrice: '$5' },
      { size: 'MEDIUM', label: 'Medium', price: 7.00, formattedPrice: '$7' },
      { size: 'LARGE', label: 'Large', price: 9.50, formattedPrice: '$9.50' },
    ],
  },

  // --------------------------------------------------------------------------
  // DELUXE PIZZA
  // --------------------------------------------------------------------------
  {
    id: 'golden-bliss',
    name: 'Golden Bliss',
    category: 'deluxe',
    categoryName: 'Deluxe Pizza',
    shortDesc: 'Signature triple-cheese blend, roasted garlic & golden herb crust',
    description: 'Signature triple-cheese blend, roasted garlic infusion, cracked pepper, and golden herb crust.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1573821663912-569905455b1c?auto=format&fit=crop&w=600&q=80',
    alt: 'Golden Bliss Pizza with triple-cheese blend and golden crust',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 7.00, formattedPrice: '$7' },
      { size: 'MEDIUM', label: 'Medium', price: 10.00, formattedPrice: '$10' },
      { size: 'LARGE', label: 'Large', price: 13.00, formattedPrice: '$13' },
    ],
  },
  {
    id: 'meat-deluxe',
    name: 'Meat Deluxe',
    category: 'deluxe',
    categoryName: 'Deluxe Pizza',
    shortDesc: 'Beef mince, crispy bacon crumbles, sliced pepperoni & diced ham',
    description: 'Seasoned beef mince, crispy bacon crumbles, sliced pepperoni, diced ham, and mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
    alt: 'Meat Deluxe Pizza loaded with beef, bacon, and pepperoni',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 6.00, formattedPrice: '$6' },
      { size: 'MEDIUM', label: 'Medium', price: 9.00, formattedPrice: '$9' },
      { size: 'LARGE', label: 'Large', price: 11.00, formattedPrice: '$11' },
    ],
  },
  {
    id: 'foodies-melt-mix',
    name: 'Foodies Melt Mix',
    category: 'deluxe',
    categoryName: 'Deluxe Pizza',
    shortDesc: 'House specialty: grilled chicken, beef & melted cheddar blend',
    description: 'House specialty with grilled chicken, seasoned beef, button mushrooms, and melted cheddar-mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=600&q=80',
    alt: 'Foodies Melt Mix Pizza with chicken, beef, and melted cheese',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 7.00, formattedPrice: '$7' },
      { size: 'MEDIUM', label: 'Medium', price: 10.00, formattedPrice: '$10' },
      { size: 'LARGE', label: 'Large', price: 13.00, formattedPrice: '$13' },
    ],
  },
  {
    id: 'foodies-supreme',
    name: 'Foodies Supreme',
    category: 'deluxe',
    categoryName: 'Deluxe Pizza',
    shortDesc: 'Spicy pepperoni, seasoned beef, peppers, mushrooms & olives',
    description: 'Spicy pepperoni, seasoned ground beef, bell peppers, fresh mushrooms, red onions, and black olives.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80',
    alt: 'Foodies Supreme Pizza with pepperoni, peppers, and olives',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 8.00, formattedPrice: '$8' },
      { size: 'MEDIUM', label: 'Medium', price: 11.00, formattedPrice: '$11' },
      { size: 'LARGE', label: 'Large', price: 14.00, formattedPrice: '$14' },
    ],
  },
  {
    id: 'chicken-hawaiian',
    name: 'Chicken Hawaiian',
    category: 'deluxe',
    categoryName: 'Deluxe Pizza',
    shortDesc: 'Grilled chicken strips, golden pineapple, cured ham & herbs',
    description: 'Grilled chicken strips, golden pineapple chunks, cured ham cuts, Italian herbs, and mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=600&q=80',
    alt: 'Chicken Hawaiian Pizza with chicken, pineapple, and ham',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 6.00, formattedPrice: '$6' },
      { size: 'MEDIUM', label: 'Medium', price: 9.00, formattedPrice: '$9' },
      { size: 'LARGE', label: 'Large', price: 11.00, formattedPrice: '$11' },
    ],
  },
  {
    id: 'fully-loaded',
    name: 'Fully Loaded',
    category: 'deluxe',
    categoryName: 'Deluxe Pizza',
    shortDesc: 'Prime meats, grilled chicken, roasted peppers & double cheese',
    description: 'Prime ground meats, grilled chicken, roasted bell peppers, onions, mushrooms, and double mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=600&q=80',
    alt: 'Fully Loaded Pizza piled high with meats and fresh toppings',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 8.00, formattedPrice: '$8' },
      { size: 'MEDIUM', label: 'Medium', price: 11.00, formattedPrice: '$11' },
      { size: 'LARGE', label: 'Large', price: 14.00, formattedPrice: '$14' },
    ],
  },
  {
    id: 'cheeseburger-pizza',
    name: 'Cheeseburger Pizza',
    category: 'deluxe',
    categoryName: 'Deluxe Pizza',
    shortDesc: 'Minced beef, melted cheddar cheese sauce, dill pickles & onions',
    description: 'Minced beef, melted cheddar cheese sauce, tangy dill pickles, diced onions, and mozzarella.',
    isPizza: true,
    image: 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&w=600&q=80',
    alt: 'Cheeseburger Pizza with minced beef, pickles, and cheddar',
    sizes: [
      { size: 'REGULAR', label: 'Regular', price: 6.00, formattedPrice: '$6' },
      { size: 'MEDIUM', label: 'Medium', price: 9.00, formattedPrice: '$9' },
      { size: 'LARGE', label: 'Large', price: 11.00, formattedPrice: '$11' },
    ],
  },
];
